// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conversationMsg.proto

package netlibp2p

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConversationMessage struct {
	Version              string            `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	ID                   string            `protobuf:"bytes,10,opt,name=ID,proto3" json:"ID,omitempty"`
	Protocol             string            `protobuf:"bytes,15,opt,name=protocol,proto3" json:"protocol,omitempty"`
	From                 string            `protobuf:"bytes,20,opt,name=from,proto3" json:"from,omitempty"`
	Timestamp            int64             `protobuf:"varint,25,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hash                 string            `protobuf:"bytes,30,opt,name=hash,proto3" json:"hash,omitempty"`
	Signature            string            `protobuf:"bytes,35,opt,name=signature,proto3" json:"signature,omitempty"`
	PubKey               string            `protobuf:"bytes,40,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	HangUp               bool              `protobuf:"varint,45,opt,name=hangUp,proto3" json:"hangUp,omitempty"`
	Data                 []byte            `protobuf:"bytes,50,opt,name=data,proto3" json:"data,omitempty"`
	Links                map[string]string `protobuf:"bytes,55,rep,name=links,proto3" json:"links,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ConversationMessage) Reset()         { *m = ConversationMessage{} }
func (m *ConversationMessage) String() string { return proto.CompactTextString(m) }
func (*ConversationMessage) ProtoMessage()    {}
func (*ConversationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversationMsg_aa7759b5288fd14b, []int{0}
}
func (m *ConversationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConversationMessage.Unmarshal(m, b)
}
func (m *ConversationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConversationMessage.Marshal(b, m, deterministic)
}
func (dst *ConversationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversationMessage.Merge(dst, src)
}
func (m *ConversationMessage) XXX_Size() int {
	return xxx_messageInfo_ConversationMessage.Size(m)
}
func (m *ConversationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConversationMessage proto.InternalMessageInfo

func (m *ConversationMessage) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ConversationMessage) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ConversationMessage) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *ConversationMessage) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ConversationMessage) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ConversationMessage) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *ConversationMessage) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *ConversationMessage) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *ConversationMessage) GetHangUp() bool {
	if m != nil {
		return m.HangUp
	}
	return false
}

func (m *ConversationMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ConversationMessage) GetLinks() map[string]string {
	if m != nil {
		return m.Links
	}
	return nil
}

func init() {
	proto.RegisterType((*ConversationMessage)(nil), "netlibp2p.ConversationMessage")
	proto.RegisterMapType((map[string]string)(nil), "netlibp2p.ConversationMessage.LinksEntry")
}

func init() {
	proto.RegisterFile("conversationMsg.proto", fileDescriptor_conversationMsg_aa7759b5288fd14b)
}

var fileDescriptor_conversationMsg_aa7759b5288fd14b = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0x94, 0x96, 0xf6, 0x40, 0x80, 0x4c, 0x41, 0x47, 0x85, 0x50, 0x04, 0x8b, 0x19,
	0xc8, 0x50, 0x06, 0x2a, 0x16, 0x06, 0xca, 0x50, 0x01, 0x4b, 0x24, 0x7e, 0x80, 0x5b, 0x4c, 0x62,
	0x35, 0xb1, 0xad, 0xd8, 0xa9, 0x94, 0x3f, 0x8f, 0x90, 0x9d, 0xd2, 0x30, 0xb0, 0xbd, 0xf7, 0xdd,
	0x3d, 0xfb, 0xf4, 0xe0, 0x6c, 0xa5, 0xd5, 0x46, 0x54, 0x96, 0x3b, 0xa9, 0xd5, 0xbb, 0xcd, 0x12,
	0x53, 0x69, 0xa7, 0xe9, 0x48, 0x09, 0x57, 0xc8, 0xa5, 0x99, 0x9a, 0xeb, 0xef, 0x08, 0x4e, 0x9f,
	0xff, 0x2e, 0x09, 0x6b, 0x79, 0x26, 0x28, 0xc2, 0xbe, 0x67, 0x52, 0x2b, 0xec, 0xc7, 0x84, 0x8d,
	0xd2, 0x5f, 0x4b, 0x8f, 0x20, 0x5a, 0xcc, 0x11, 0x02, 0x8c, 0x16, 0x73, 0x3a, 0x81, 0x61, 0x78,
	0x75, 0xa5, 0x0b, 0x3c, 0x0e, 0x74, 0xe7, 0x29, 0x85, 0xbd, 0xaf, 0x4a, 0x97, 0x38, 0x0e, 0x3c,
	0x68, 0x7a, 0x09, 0x23, 0x27, 0x4b, 0x61, 0x1d, 0x2f, 0x0d, 0x5e, 0xc4, 0x84, 0xf5, 0xd2, 0x0e,
	0xf8, 0x44, 0xce, 0x6d, 0x8e, 0x57, 0x6d, 0xc2, 0x6b, 0x9f, 0xb0, 0x32, 0x53, 0xdc, 0xd5, 0x95,
	0xc0, 0x9b, 0x30, 0xe8, 0x00, 0x3d, 0x87, 0x81, 0xa9, 0x97, 0xaf, 0xa2, 0x41, 0x16, 0x46, 0x5b,
	0xe7, 0x79, 0xce, 0x55, 0xf6, 0x61, 0xf0, 0x2e, 0x26, 0x6c, 0x98, 0x6e, 0x9d, 0xff, 0xe1, 0x93,
	0x3b, 0x8e, 0xd3, 0x98, 0xb0, 0xc3, 0x34, 0x68, 0xfa, 0x04, 0xfd, 0x42, 0xaa, 0xb5, 0xc5, 0x87,
	0xb8, 0xc7, 0x0e, 0xa6, 0xb7, 0xc9, 0xae, 0xa0, 0xe4, 0x9f, 0x72, 0x92, 0x37, 0xbf, 0xfb, 0xa2,
	0x5c, 0xd5, 0xa4, 0x6d, 0x6e, 0x32, 0x03, 0xe8, 0x20, 0x3d, 0x81, 0xde, 0x5a, 0x34, 0x48, 0xc2,
	0x3d, 0x5e, 0xd2, 0x31, 0xf4, 0x37, 0xbc, 0xa8, 0x05, 0x46, 0x81, 0xb5, 0xe6, 0x31, 0x9a, 0x91,
	0xe5, 0x20, 0x94, 0x75, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x72, 0xa0, 0x50, 0xe3, 0xab, 0x01,
	0x00, 0x00,
}
