// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go-network-ipfs/conversationMsg.proto

package netlibp2p

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConversationMessage struct {
	Version              string   `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	ID                   string   `protobuf:"bytes,10,opt,name=ID,proto3" json:"ID,omitempty"`
	Protocol             string   `protobuf:"bytes,15,opt,name=protocol,proto3" json:"protocol,omitempty"`
	From                 string   `protobuf:"bytes,20,opt,name=from,proto3" json:"from,omitempty"`
	Timestamp            int64    `protobuf:"varint,25,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature            string   `protobuf:"bytes,30,opt,name=signature,proto3" json:"signature,omitempty"`
	PubKey               string   `protobuf:"bytes,35,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	HangUp               bool     `protobuf:"varint,40,opt,name=hangUp,proto3" json:"hangUp,omitempty"`
	Message              *any.Any `protobuf:"bytes,45,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConversationMessage) Reset()         { *m = ConversationMessage{} }
func (m *ConversationMessage) String() string { return proto.CompactTextString(m) }
func (*ConversationMessage) ProtoMessage()    {}
func (*ConversationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversationMsg_760f2882cd4fc879, []int{0}
}
func (m *ConversationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConversationMessage.Unmarshal(m, b)
}
func (m *ConversationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConversationMessage.Marshal(b, m, deterministic)
}
func (dst *ConversationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversationMessage.Merge(dst, src)
}
func (m *ConversationMessage) XXX_Size() int {
	return xxx_messageInfo_ConversationMessage.Size(m)
}
func (m *ConversationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConversationMessage proto.InternalMessageInfo

func (m *ConversationMessage) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ConversationMessage) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ConversationMessage) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *ConversationMessage) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ConversationMessage) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ConversationMessage) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *ConversationMessage) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *ConversationMessage) GetHangUp() bool {
	if m != nil {
		return m.HangUp
	}
	return false
}

func (m *ConversationMessage) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*ConversationMessage)(nil), "ipfsnet.ConversationMessage")
}

func init() {
	proto.RegisterFile("go-network-ipfs/conversationMsg.proto", fileDescriptor_conversationMsg_760f2882cd4fc879)
}

var fileDescriptor_conversationMsg_760f2882cd4fc879 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd0, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x06, 0x60, 0x5a, 0x75, 0xdd, 0x8e, 0xa0, 0x10, 0x87, 0x9c, 0x0d, 0x91, 0xa2, 0x08, 0xbd,
	0x69, 0x0b, 0xfa, 0x04, 0xe2, 0x6e, 0x86, 0x78, 0x53, 0xf0, 0x01, 0xd2, 0x91, 0xc6, 0xe0, 0x9a,
	0x13, 0x92, 0x54, 0xe9, 0x33, 0xf8, 0xd2, 0xd2, 0x74, 0x75, 0xde, 0xf5, 0xff, 0xfe, 0x73, 0x0a,
	0x39, 0xf0, 0x20, 0x29, 0xd7, 0xc2, 0x7f, 0x93, 0xfd, 0xcc, 0x95, 0x69, 0x5c, 0xb9, 0x23, 0xfd,
	0x25, 0xac, 0xe3, 0x5e, 0x91, 0x7e, 0x73, 0xb2, 0x30, 0x96, 0x3c, 0xb1, 0x64, 0xe8, 0xb4, 0xf0,
	0xeb, 0x95, 0x24, 0x92, 0x7b, 0x51, 0x06, 0xae, 0xbb, 0xa6, 0xe4, 0xba, 0x1f, 0x67, 0xee, 0x7e,
	0x62, 0xb8, 0x7a, 0xf9, 0xbf, 0x2d, 0x9c, 0xe3, 0x52, 0x30, 0x84, 0x64, 0x30, 0x45, 0x1a, 0xcf,
	0xd2, 0x28, 0x5b, 0x54, 0x53, 0x64, 0x17, 0x10, 0x6f, 0x37, 0x08, 0x01, 0xe3, 0xed, 0x86, 0xad,
	0x61, 0x1e, 0x7e, 0xb5, 0xa3, 0x3d, 0x5e, 0x06, 0xfd, 0xcb, 0x8c, 0xc1, 0x69, 0x63, 0xa9, 0xc5,
	0x65, 0xf0, 0xf0, 0xcd, 0x6e, 0x60, 0xe1, 0x55, 0x2b, 0x9c, 0xe7, 0xad, 0xc1, 0x55, 0x1a, 0x65,
	0x27, 0xd5, 0x11, 0x86, 0xd6, 0x29, 0xa9, 0xb9, 0xef, 0xac, 0xc0, 0xdb, 0xb0, 0x76, 0x04, 0x76,
	0x0d, 0x33, 0xd3, 0xd5, 0xaf, 0xa2, 0xc7, 0xfb, 0x50, 0x1d, 0xd2, 0xe0, 0x1f, 0x5c, 0xcb, 0x77,
	0x83, 0x59, 0x1a, 0x65, 0xf3, 0xea, 0x90, 0x58, 0x01, 0x49, 0x3b, 0x3e, 0x08, 0xf3, 0x34, 0xca,
	0xce, 0x1f, 0x97, 0xc5, 0x78, 0x8a, 0x62, 0x3a, 0x45, 0xf1, 0xac, 0xfb, 0x6a, 0x1a, 0xaa, 0x67,
	0x81, 0x9f, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x6a, 0xa0, 0x5e, 0x61, 0x01, 0x00, 0x00,
}
